version: '2'
services:
    build:
        image: empathicqubit/vscode-cc65-debugger-build
        user: "1000"
        volumes:
            - ..:/mnt
        working_dir: /mnt
        command:
            - 'bash'
            - '-c'
            - 'pnpm install && pnpm jest:compile && pnpm build:test && USE_XVFB=1 pnpm jest src/__tests__/runtime-other-platforms.test.ts'
