name: Check 🔍

on:
  pull_request:
    branches:
        - master
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  linux-build:
    name: 🐧
    runs-on: ubuntu-22.04
    container: empathicqubit/vscode-cc65-debugger-build

    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          ./**/*
        key: check-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}

    - uses: actions/checkout@v4
      name: 🔄 Checkout Code
      with:
          ref: "${{ github.events.inputs.ref }}"
          submodules: recursive
    - run: git config --global --add safe.directory /__w/vscode-cc65-debugger/vscode-cc65-debugger
      name: 🔓 Mark repo directory as safe
    - run: pnpm install --shamefully-hoist
      name: 📦 Install node modules
    - run: pnpm build:test
      name: 🛠️ Build tests

  linux-test:
    name: 🧪🐧
    needs: linux-build
    runs-on: ubuntu-22.04
    container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      fail-fast: false
      matrix:
          include:
              - vice_version: 3.8
                machine: nes
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.8/src

              - vice_version: 3.8
                machine: pet
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.8/src

              - vice_version: 3.8
                machine: c64
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.8/src
              - vice_version: trunk
                machine: c64
                vice_directory: ""

    steps:
    - name: Load build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          ./**/*
        key: check-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}
    - run: git config --global --add safe.directory /__w/vscode-cc65-debugger/vscode-cc65-debugger
      name: 🔓 Mark repo directory as safe

    - run: |
        ln -s $PWD/system /usr/local/share/vice
        ln -s $PWD/system /usr/local/lib/vice
        ln -s $PWD/system /usr/lib/vice
        ln -s $PWD/system /usr/share/vice
        ls -l /usr/local/share
      name: 🔗 Symlink VICE data folder

    - run: TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.${{ matrix.machine }} VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
      name: 🏃 Run tests
      continue-on-error: true

    - name: Publish test report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "🧪🐧📋: VICE ${{ matrix.vice_version }}: ${{ matrix.machine }}"
        path: "./obj/noncompile.testrun.xml"
        reporter: jest-junit
