name: Check

on:
  pull_request:
    branches:
        - master
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

jobs:
  kill_old_jobs:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  mac-build:

    runs-on: macos-10.15
    #container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      fail-fast: false
      matrix:
          include:
              - vice_directory: "vice-x86-64-gtk3-3.6.1"
                vice_version: "3.6.1"

    steps:
    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"
    - run: brew install sevenzip coreutils visual-studio-code
    - run: curl -sL -o "$HOME/VICE.dmg" "https://sourceforge.net/projects/vice-emu/files/releases/binaries/macosx/${{ matrix.vice_directory }}.dmg/download"
    - run: ls -lha "$HOME/VICE.dmg"
    - run: 7z x "$HOME/VICE.dmg"
    - run: mv ${{ matrix.vice_directory }}/${{ matrix.vice_directory }} /Applications
    - run: cd /Applications/${{ matrix.vice_directory }}/bin && chmod -R a+x . && chmod a+x ../VICE.app/Contents/Resources/script && chmod -R a+x ../VICE.app/Contents/Resources/bin && ./x64sc -help

    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: VICE_DIRECTORY="/Applications/${{ matrix.vice_directory }}/bin" pnpm build:test
    - continue-on-error: true
      run: VICE_DIRECTORY="/Applications/${{ matrix.vice_directory }}/bin" USE_XVFB=1 pnpm test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "Test Results: Mac: VICE ${{ matrix.vice_version }}"
        path: "*.testrun.xml"
        reporter: jest-junit

  linux-build:
    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
          ./**/*
        key: check-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}

    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"
    - run: git config --global --add safe.directory /__w/vscode-cc65-debugger/vscode-cc65-debugger
    - run: pnpm install --shamefully-hoist
    - run: pnpm build:test

  linux-test:
    needs: linux-build
    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      fail-fast: false
      matrix:
          include:
              - vice_version: 3.6
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.6/src
              - vice_version: trunk
                vice_directory:

    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
          ./**/*
        key: check-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}

    - run: ln -s $PWD/system /usr/local/share/vice
    - run: ln -s $PWD/system /usr/local/lib/vice
    - run: ln -s $PWD/system /usr/lib/vice
    - run: ln -s $PWD/system /usr/share/vice
    - run: ls -l /usr/local/share

    - run: rm *.testrun.xml && TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.c64 VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
      continue-on-error: true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "Test Results: Linux: VICE ${{ matrix.vice_version }}: C64"
        path: "*.testrun.xml"
        reporter: jest-junit

    - run: rm *.testrun.xml && TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.pet VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
      continue-on-error: true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "Test Results: Linux: VICE ${{ matrix.vice_version }}: PET"
        path: "*.testrun.xml"
        reporter: jest-junit

    - run: rm *.testrun.xml && TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.nes VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
      continue-on-error: true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "Test Results: Linux: NES"
        path: "*.testrun.xml"
        reporter: jest-junit
