name: Generate 👷

on:
  push:
    branches:
      - master

jobs:
  generate:
    name: Generate 👷
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      name: 🔄 Checkout Code
    - name: 👷 Release Maintenance
      # You may pin to the exact commit or the version.
      # uses: google-github-actions/release-please-action@81fdb5157c2201f0927147dd6cb2dcb1f128e3d0
      uses: googleapis/release-please-action@v4.1.3
      with:
        # GitHub token for creating and grooming release PRs, e.g., secrets.GITHUB_TOKEN
        token: ${{secrets.REPO_GITHUB_TOKEN}}
        # what type of release is this, one of (ruby, python, node, terraform-module)
        release-type: node
