name: MacOS

on:
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

jobs:
  build:

    runs-on: macos-10.15
    #container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      fail-fast: false
      matrix:
          include:
              - vice_version: ""
                vice_directory: VICE_DIRECTORY=

    steps:
    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"
    - run: node -e "console.log('PROCESSOR', process.arch)"
    - run: brew install vice
    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm build:test
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm testmerge
