name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:13-buster

    strategy:
      matrix:
          vice-version: [3.5] #Add versions here

    steps:
    - uses: actions/checkout@v2
    - run: apt update
    - run: apt build-dep --no-install-recommends -y vice
    - run: npm install -g pnpm@5.5.10
    - run: pnpm install --shamefully-hoist
    - run: pnpm package
      env:
        CI: true
