name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:13

    strategy:
      matrix:
        testerson: [1] #Add versions here

    steps:
    - uses: actions/checkout@v2
    - run: npm install -g pnpm@5.5.10
    - run: pnpm install --shamefully-hoist
    - run: pnpm package
      env:
        CI: true
