name: Check

on:
  pull_request:
    branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build

    strategy:
      matrix:
          vice-version: [3.5] #Add versions here

    steps:
    - uses: actions/checkout@v2
    - run: pnpm install --shamefully-hoist
    - run: pnpm package
