name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:13-buster

    strategy:
      matrix:
          vice-version: [3.5] #Add versions here

    steps:
    - uses: actions/checkout@v2
    - run: sed -i 's@debian.org/debian [[:alpha:]]* main@& contrib@g' /etc/apt/sources.list
    - run: grep 'debian.org/debian [[:alpha:]]* main' /etc/apt/sources.list | grep -v '#' | sed -e 's/^deb/deb-src/g' >> /etc/apt/sources.list
    - run: apt-get update
    - run: apt-get build-dep --no-install-recommends -y vice
    - run: apt-get install dos2unix
    - run: npm install -g pnpm@5.5.10
    - run: pnpm install --shamefully-hoist
    - run: pnpm package
      env:
        CI: true
