name: Publish

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'refs/tags/vFIXME'
    release:
        types:
        - edited

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build
    env:
      TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag }}
    steps:
    - run: curl -sL https://github.com/empathicqubit/vscode-cc65-vice-debug/releases/download/$TAG_NAME/cc65-vice-${TAG_NAME/#v/}.vsix > cc65-vice.vsix
    - run: pnpx -y -p @empathicqubit/vsce vsce publish --packagePath cc65-vice.vsix -p ${{ secrets.MARKETPLACE_TOKEN }}
    - run: pnpx -y ovsx publish ./cc65-vice.vsix -p ${{ secrets.OPENVSX_TOKEN }}