name: Publish

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'vFIXME'

jobs:
  publish:
    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build
    env:
      TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag }}
    steps:
    - uses: actions/checkout@v2
    - run: curl -sL https://github.com/empathicqubit/vscode-cc65-vice-debug/releases/download/$TAG_NAME/cc65-vice-$(echo "${TAG_NAME}" | sed 's/^v//g').vsix > cc65-vice.vsix
    - run: mkdir dist && CHECKSUM=$(sha256sum cc65-vice.vsix) node ./vimspector-gadget.js
      env:
          TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag }}
    - name: Upload gadget definition
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/gadget.json
        asset_name: vimspector-gadget.json
        tag: ${{ github.event.release.tag_name || github.event.inputs.tag }}
        overwrite: true
    - run: pnpx -y -p @entan.gl/vsce vsce publish --packagePath cc65-vice.vsix -p ${{ secrets.MARKETPLACE_TOKEN }}
      id: vsce
      continue-on-error: true
    - run: pnpx -y ovsx publish ./cc65-vice.vsix -p ${{ secrets.OPENVSX_TOKEN }}
      id: ovsx
      continue-on-error: true
    - name: update release
      if: steps.vsce.outcome == 'success' && steps.ovsx.outcome == 'success'
      id: update_release_success
      run: |
          curl -sL "https://api.github.com/repos/empathicqubit/vscode-cc65-vice-debug/releases/tags/${TAG_NAME}" \
          | node -e 'process.stdin.once("data", data => { console.log(JSON.parse(data.toString()).id ) })' \
          | xargs -I'{}' curl -X PATCH \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            -sL 'https://api.github.com/repos/empathicqubit/vscode-cc65-vice-debug/releases/{}' \
            -d '{"name": "cc65-vice '"${TAG_NAME}"' (Published)"}'
      env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag }}
    - name: update release
      if: steps.vsce.outcome == 'failure' || steps.ovsx.outcome == 'failure'
      id: update_release_failed
      run: |
          curl -sL "https://api.github.com/repos/empathicqubit/vscode-cc65-vice-debug/releases/tags/${TAG_NAME}" \
          | node -e 'process.stdin.once("data", data => { console.log(JSON.parse(data.toString()).id ) })' \
          | xargs -I'{}' curl -X PATCH \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            -sL 'https://api.github.com/repos/empathicqubit/vscode-cc65-vice-debug/releases/{}' \
            -d '{"name": "cc65-vice '"${TAG_NAME}"' (Failed Publish)"}'
      env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag }}
