name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'vFIXME'
    release:
        types:
        - published

jobs:
  darwin-compiler:

    runs-on: macos-10.15
    #container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      matrix:
          include:
              - vice_version: ""
                vice_directory: VICE_DIRECTORY=

    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ./dist/cc65/bin_darwin_*/*
        key: release-${{ github.run_id }}-${{ github.run_number }}

    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"
    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm submodules
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm compiler

  build:
    needs: darwin-compiler
    outputs:
      filename: ${{ steps.get_filename.outputs.filename }}

    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      matrix:
          include:
              - vice_version: 3.6
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.6/src

    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ./dist/cc65/bin_darwin_*/**/*
        key: release-${{ github.run_id }}-${{ github.run_number }}

    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.inputs.tag || github.event.release.tag_name }}

    - run: pnpm install --shamefully-hoist
    - run: ln -s $PWD/system /usr/local/share/vice
    - run: ln -s $PWD/system /usr/local/lib/vice
    - run: ln -s $PWD/system /usr/lib/vice
    - run: ln -s $PWD/system /usr/share/vice
    - run: ls -l /usr/local/share
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm package
    - run: 7z l cc65-vice*.vsix

    - run: echo -n "::set-output name=filename::" && echo cc65-vice-*.vsix
      id: get_filename

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: cc65-vice ${{ github.event.inputs.tag || github.event.release.tag_name }} (Unpublished)
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.get_filename.outputs.filename }}
        asset_name: ${{ steps.get_filename.outputs.filename }}
        tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
        overwrite: true
