name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'refs/tags/vFIXME'
    release:
        types:
        - published

jobs:
  build:
    outputs:
      filename: ${{ steps.get_filename.outputs.filename }}

    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build

    strategy:
      matrix:
          include:
              - vice_version:
                vice_directory: VICE_DIRECTORY=/vices/vice-3.5-build/src
             #- vice_version: trunk
             #  vice_directory:

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.events.inputs.tag }}
    - run: pnpm install --shamefully-hoist
    - run: ln -s $PWD/system /usr/local/share/vice
    - run: ln -s $PWD/system /usr/local/lib/vice
    - run: ln -s $PWD/system /usr/lib/vice
    - run: ln -s $PWD/system /usr/share/vice
    - run: ls -l /usr/local/share
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm package
    - run: 7z l cc65-vice*.vsix

    - run: echo -n "::set-output name=filename::" && echo cc65-vice-*.vsix
      id: get_filename

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.get_filename.outputs.filename }}
        asset_name: ${{ steps.get_filename.outputs.filename }}
        tag: ${{ github.event.inputs.tag || github.ref }}
        overwrite: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build
    - run: curl -sL https://github.com/empathicqubit/vscode-cc65-vice-debug/releases/download/${{ github.ref.replace('refs/tags/', '') }}/${{ needs.build.outputs.filename } > cc65-vice.vsix
    - run: pnpx -y -p @empathicqubit/vsce vsce publish --packagePath cc65-vice.vsix -p ${{ secrets.MARKETPLACE_TOKEN }}
    - run: pnpx -y ovsx publish ./cc65-vice-*.vsix -p ${{ secrets.OPENVSX_TOKEN }}