name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'vFIXME'
    release:
        types:
        - published

jobs:
  darwin-compiler:

    runs-on: macos-10.15
    #container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      matrix:
          include:
              - vice_version: ""
                vice_directory: VICE_DIRECTORY=
                tag_ref: ${{ github.event.inputs.tag || github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ matrix.tag_ref }}
    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm submodules
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm compiler

    - uses: actions/upload-artifact@v2
      with:
        name: darwin-compiler
        path: dist/cc65/bin_darwin_*/*

  build:
    needs: darwin-compiler
    outputs:
      filename: ${{ steps.get_filename.outputs.filename }}

    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      matrix:
          include:
              - vice_version: 3.6
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.6/src

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ matrix.tag_ref }}

    - run: cd src/__tests__ && 7z a ../../asm-project-template.zip ./asm-project
    - name: Upload Assembly Template to release
      if: !github.event.inputs.tag
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: cc65-vice ${{ matrix.tag_ref }} (Unpublished)
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: asm-project-template.zip
        asset_name: ${{ steps.get_filename.outputs.filename }}
        tag: ${{ matrix.tag_ref }}
        overwrite: true

    - run: cd src/__tests__ && 7z a ../../c-project-template.zip ./c-project-template
    - name: Upload C Template to release
      if: !github.event.inputs.tag
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: cc65-vice ${{ matrix.tag_ref }} (Unpublished)
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: c-project-template.zip
        asset_name: ${{ steps.get_filename.outputs.filename }}
        tag: ${{ matrix.tag_ref }}
        overwrite: true

    - run: pnpm install --shamefully-hoist
    - run: ln -s $PWD/system /usr/local/share/vice
    - run: ln -s $PWD/system /usr/local/lib/vice
    - run: ln -s $PWD/system /usr/lib/vice
    - run: ln -s $PWD/system /usr/share/vice
    - run: ls -l /usr/local/share

    - uses: actions/download-artifact@v2
      with:
        name: darwin-compiler
        path: dist/cc65

    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm package
    - run: 7z l cc65-vice*.vsix

    - run: echo -n "::set-output name=filename::" && echo cc65-vice-*.vsix
      id: get_filename

    - uses: actions/upload-artifact@v2
      with:
        name: cc65-vice.vsix
        path: cc65-vice*.vsix

    - name: Upload binaries to release
      if: !github.event.inputs.tag
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: cc65-vice ${{ matrix.tag_ref }} (Unpublished)
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.get_filename.outputs.filename }}
        asset_name: ${{ steps.get_filename.outputs.filename }}
        tag: ${{ matrix.tag_ref }}
        overwrite: true
