name: Release

on:
  release:
    types:
        - published

jobs:
  build:

    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build

    strategy:
      matrix:
        vice-version: [3.5] #Add versions here

    steps:
    - uses: actions/checkout@v2
    - run: pnpm install --shamefully-hoist
    - run: pnpm package

    - run: echo -n "::set-output name=filename::" && echo cc65-vice-*.vsix
      id: get_filename
    - uses: bruceadams/get-release@v1.2.2
      id: get_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ steps.get_filename.outputs.filename }}
        asset_name: ${{ steps.get_filename.outputs.filename }}
        asset_content_type: application/zip

    - run: pnpm run publish -- --packagePath ./cc65-vice-*.vsix -p ${{ secrets.MARKETPLACE_TOKEN }}
