name: Trash

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'refs/tags/vFIXME'

jobs:
  build:

    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build

    steps:
    - env:
        GITHUB_REF: ${{ github.event.inputs.tag || github.ref }}
      run: echo "Hello $GITHUB_REF"
