name: Trash

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'refs/tags/vFIXME'

jobs:
  build:

    runs-on: ubuntu-latest
    container: empathicqubit/vscode-cc65-vice-debug-build

    steps:
    - run: echo "Hallo Leute" > testerson.txt
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: testerson.txt
        asset_name: testerson.txt
        tag: ${{ github.event.inputs.tag || github.ref }}
        overwrite: true