name: Windows

on:
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

jobs:

  build:

    runs-on: windows-latest

    strategy:
      matrix:
          vice-version: [3.5] #Add versions here

    steps:
    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"

    - run: git config --global core.autocrlf input
      shell: bash

    - name: Checkout VICE
      uses: actions/checkout@v2
      with:
          repository: Vice-Team/svn-mirror
          path: src/tests/vicedir

    - name: Install GTK3 Dependencies if Applicable
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          zip
          subversion
          git
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-giflib
          mingw-w64-x86_64-lame
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-flac
          mingw-w64-x86_64-icoutils
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-gtk3

    - name: Build VICE
      id: build
      shell: msys2 {0}
      run: |
        cd ./src/tests/vicedir
        ./autogen.sh
        ./configure --enable-headless --disable-arch --disable-pdf-docs --disable-ethernet --disable-cpuhistory --enable-headless
        make -j$(nproc) -s

    - run: choco install nodejs-lts
    - run: choco install winvice-nightly cc65-compiler svn make python3
    - run: pip3 install --user fonttools
    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: mkdir dist
    - run: pnpm tisk
    - run: pnpm nonjs
    - run: pnpm mocha:prepublish
    - run: unzip -l cc65-vice*.vsix
