name: Windows

on:
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
          vice-version: [3.5] #Add versions here

    steps:
    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"
    - run: choco install nodejs-lts
    - run: choco install winvice-nightly cc65-compiler svn make python3
    - run: pip3 install --user fonttools
    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: mkdir dist
    - run: pnpm tisk
    - run: pnpm nonjs
    - run: $env:VICE_DIRECTORY="$((Get-Item C:/ProgramData/chocolatey/lib/winvice-nightly/tools/GTK*/bin).FullName)"; pnpm mocha:prepublish
    - run: unzip -l cc65-vice*.vsix
